//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Estequeometria.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_Estequeometria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos; standalone=&apos;yes&apos; ?&gt;
        ///&lt;!--Archivo para el soft de práctica de estequiometría para ciegos--&gt;
        ///&lt;elementos&gt;
        ///	&lt;metales&gt; 
        ///	  &lt;metal&gt;
        ///	  &lt;nombre&gt;&quot;Litio&quot;&lt;/nombre&gt;
        ///	  &lt;simbolo&gt;&quot;Li&quot;&lt;/simbolo&gt;
        ///	  &lt;valencias&gt;
        ///		&lt;valor&gt;&quot;1&quot;&lt;/valor&gt;
        ///	  &lt;/valencias&gt;
        ///	  &lt;/metal&gt;
        ///	  
        ///	  &lt;metal&gt;
        ///	  &lt;nombre&gt;&quot;Sodio&quot;&lt;/nombre&gt;
        ///	  &lt;simbolo&gt;&quot;Na&quot;&lt;/simbolo&gt;
        ///	  &lt;valencias&gt;
        ///		&lt;valor&gt;&quot;1&quot;&lt;/valor&gt;
        ///	  &lt;/valencias&gt;
        ///	  &lt;/metal&gt;
        ///	 
        ///	 &lt;metal&gt;
        ///	 &lt;nombre&gt;&quot;Potasio&quot;&lt;/nombre&gt;
        ///	  &lt;simbolo&gt;&quot;K&quot;&lt;/simbolo&gt;
        ///	  &lt;va [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string elementos {
            get {
                return ResourceManager.GetString("elementos", resourceCulture);
            }
        }
    }
}
